"""remove unused columns 2

Revision ID: 2f389f59cdf0
Revises: 2bbe2db4e889
Create Date: 2025-04-13 10:14:16.781344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f389f59cdf0'
down_revision: Union[str, None] = '2bbe2db4e889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'tags')
    op.drop_column('products', 'caption')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('caption', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
