"""add embedding column

Revision ID: 409001696b35
Revises: 999a545df60a
Create Date: 2025-04-12 16:13:18.570969

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = "409001696b35"
down_revision: Union[str, None] = "999a545df60a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.add_column(
        "products",
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "embedding")
    op.execute("DROP EXTENSION IF EXISTS vector;")
    # ### end Alembic commands ###
