services:
  db:
    ports:
      - "5432:5432"
    image: ankane/pgvector
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devdb
